### ISSUE TITLE
error handler don't work

### ISSUE THREAD

**Issue by jeetiss** [tradable/tradable-core#2]
method [resolveDeferred](https://github.com/tradable/tradable-embed-core/blob/master/src/tradable-embed.js#L1533) [rejects](https://github.com/tradable/tradable-embed-core/blob/master/src/tradable-embed.js#L484) without arguments

**Comment by oizulain** [comment]
Resolved in commit aa32b82ae6f36fa7aa1b434a5e6064db7a475386
